input {
  file {
    path => "/var/log/app/*.log"
    codec => json
    mode => "tail"
    start_position => "beginning"
  }
}

filter {
  mutate {
    remove_field => ["[log][file]", "[host]", "[event]", "[@version]"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => "true"
    data_stream_type => "logs"
    data_stream_dataset => "stadium"
    data_stream_namespace => "dev"
    user => "${LOGSTASH_USERNAME}"
    password => "${LOGSTASH_PASSWORD}"
  }
}
